version: '3.8'
services:
  vscode:
    stdin_open: true
    tty: true
    build: .
    container_name: vscode-container
    image: vscode-container
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./vscode_data:/root/.vscode
      - ./workspace:/workspace
    working_dir: /workspace
    command: ["tail", "-f", "/dev/null"]
    ipc: host
    network_mode: host

volumes:
  vscode_data:
    driver: local
  workspace:
    driver: local
